/// HTCondor submit file generation for multi-genome batch annotation.
///
/// Generates a `.sub` file that submits each genome as a separate job
/// (or an array of jobs) to an HTCondor cluster. Each job runs the full
/// myconote-cli pipeline for one genome.
///
/// Usage:
///   myconote-cli batch genomes/ --condor [--condor-cpus 8] [--condor-mem 32G]
///                                        [--condor-disk 50G] [--condor-queue <queue>]
///                                        [--condor-extra <file>]
use std::path::{Path, PathBuf};

use crate::utils::error::{MycoNoteError, Result};

/// HTCondor configuration.
#[derive(Debug, Clone)]
pub struct CondorConfig {
    /// CPUs per job.
    pub cpus: usize,
    /// Memory per job (e.g. "32G", "16384").
    pub memory: String,
    /// Disk per job (e.g. "50G").
    pub disk: String,
    /// HTCondor accounting group / queue.
    pub queue: Option<String>,
    /// Path to extra submit directives to append.
    pub extra_file: Option<PathBuf>,
    /// Maximum concurrent jobs (max_idle).
    pub max_idle: Option<usize>,
}

impl Default for CondorConfig {
    fn default() -> Self {
        Self {
            cpus: 8,
            memory: "32G".to_string(),
            disk: "50G".to_string(),
            queue: None,
            extra_file: None,
            max_idle: None,
        }
    }
}

/// A single genome entry for the Condor job array.
pub struct CondorGenome {
    pub name: String,
    pub fasta_path: String,
    pub kingdom: String,
    pub species: Option<String>,
    pub genetic_code: u8,
    pub locus_prefix: Option<String>,
}

/// Generate an HTCondor submit file and a per-genome argument list.
///
/// Creates:
///   <batch_dir>/condor.sub        — the submit file
///   <batch_dir>/condor_genomes.txt — one genome per line (for $(Process) indexing)
///   <batch_dir>/run_genome.sh     — the wrapper script each job executes
///
/// Returns the path to the submit file.
pub fn generate_condor_submit(
    batch_dir: &Path,
    genomes: &[CondorGenome],
    config: &CondorConfig,
    stages: &[&str],
    threads: usize,
) -> Result<PathBuf> {
    if genomes.is_empty() {
        return Err(MycoNoteError::BatchError(
            "no genomes provided for Condor submission".to_string(),
        ));
    }

    std::fs::create_dir_all(batch_dir)
        .map_err(|e| MycoNoteError::BatchError(format!("cannot create {}: {}", batch_dir.display(), e)))?;

    // ── 1. Write genome list ──
    let genome_list_path = batch_dir.join("condor_genomes.txt");
    let mut genome_lines = Vec::new();
    for g in genomes {
        // Tab-separated: name, fasta_path, kingdom, species, genetic_code, locus_prefix
        genome_lines.push(format!(
            "{}\t{}\t{}\t{}\t{}\t{}",
            g.name,
            g.fasta_path,
            g.kingdom,
            g.species.as_deref().unwrap_or("auto"),
            g.genetic_code,
            g.locus_prefix.as_deref().unwrap_or("GENE"),
        ));
    }
    std::fs::write(&genome_list_path, genome_lines.join("\n") + "\n")
        .map_err(|e| MycoNoteError::BatchError(format!("cannot write genome list: {}", e)))?;

    // ── 2. Write wrapper script ──
    let script_path = batch_dir.join("run_genome.sh");
    let stages_str = stages.join(",");
    let script = format!(
        r#"#!/bin/bash
# Auto-generated by myconote-cli batch --condor
# Each HTCondor job runs this script with a line number from condor_genomes.txt
set -euo pipefail

LINE_NUM=$((CONDOR_PROCESS_ID + 1))
GENOME_LINE=$(sed -n "${{LINE_NUM}}p" "{genome_list}")

NAME=$(echo "$GENOME_LINE" | cut -f1)
FASTA=$(echo "$GENOME_LINE" | cut -f2)
KINGDOM=$(echo "$GENOME_LINE" | cut -f3)
SPECIES=$(echo "$GENOME_LINE" | cut -f4)
GENETIC_CODE=$(echo "$GENOME_LINE" | cut -f5)
LOCUS_PREFIX=$(echo "$GENOME_LINE" | cut -f6)

OUTDIR="{batch_dir}/$NAME"
mkdir -p "$OUTDIR"

echo "[$(date -Iseconds)] Starting pipeline for $NAME"

SORTED="$OUTDIR/${{NAME}}_sorted.fa"
MASKED="$OUTDIR/${{NAME}}_masked.fa"
PREDICT_DIR="$OUTDIR/predict_out"
ANNOTATE_DIR="$OUTDIR/annotate_out"
SUBMIT_DIR="$OUTDIR/submit_out"

STAGES="{stages}"

run_stage() {{
    local stage=$1
    case "$STAGES" in
        *"$stage"*) return 0 ;;
        *) return 1 ;;
    esac
}}

if run_stage sort; then
    echo "[$(date -Iseconds)] $NAME | sort | started"
    myconote-cli sort "$FASTA" --output "$SORTED" --min-length 500
    echo "[$(date -Iseconds)] $NAME | sort | done"
else
    SORTED="$FASTA"
fi

if run_stage mask; then
    echo "[$(date -Iseconds)] $NAME | mask | started"
    myconote-cli mask "$SORTED" --output "$MASKED" --engine repeatmodeler --threads {threads}
    echo "[$(date -Iseconds)] $NAME | mask | done"
else
    MASKED="$SORTED"
fi

if run_stage predict; then
    echo "[$(date -Iseconds)] $NAME | predict | started"
    PREDICT_ARGS="--output $PREDICT_DIR --kingdom $KINGDOM --threads {threads}"
    [ "$SPECIES" != "auto" ] && PREDICT_ARGS="$PREDICT_ARGS --species $SPECIES"
    [ "$LOCUS_PREFIX" != "GENE" ] && PREDICT_ARGS="$PREDICT_ARGS --locus-prefix $LOCUS_PREFIX"
    myconote-cli predict "$MASKED" $PREDICT_ARGS
    echo "[$(date -Iseconds)] $NAME | predict | done"
fi

if run_stage annotate; then
    echo "[$(date -Iseconds)] $NAME | annotate | started"
    GFF="$PREDICT_DIR/consensus.gff3"
    ANNOTATE_ARGS="--fasta $MASKED --output $ANNOTATE_DIR --kingdom $KINGDOM --threads {threads}"
    [ "$LOCUS_PREFIX" != "GENE" ] && ANNOTATE_ARGS="$ANNOTATE_ARGS --locus-prefix $LOCUS_PREFIX"
    [ "$GENETIC_CODE" != "1" ] && ANNOTATE_ARGS="$ANNOTATE_ARGS --genetic-code $GENETIC_CODE"
    myconote-cli annotate "$GFF" $ANNOTATE_ARGS
    echo "[$(date -Iseconds)] $NAME | annotate | done"
fi

if run_stage submit; then
    echo "[$(date -Iseconds)] $NAME | submit | started"
    SUBMIT_GFF="$ANNOTATE_DIR/annotated.gff3"
    [ ! -f "$SUBMIT_GFF" ] && SUBMIT_GFF="$PREDICT_DIR/consensus.gff3"
    myconote-cli submit "$SUBMIT_GFF" --fasta "$MASKED" --output "$SUBMIT_DIR" --locus-prefix "$LOCUS_PREFIX" --genetic-code "$GENETIC_CODE"
    echo "[$(date -Iseconds)] $NAME | submit | done"
fi

echo "[$(date -Iseconds)] $NAME | ALL | done"
"#,
        genome_list = genome_list_path.display(),
        batch_dir = batch_dir.display(),
        stages = stages_str,
        threads = threads,
    );

    std::fs::write(&script_path, &script)
        .map_err(|e| MycoNoteError::BatchError(format!("cannot write wrapper script: {}", e)))?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(&script_path, perms)
            .map_err(|e| MycoNoteError::BatchError(format!("cannot chmod script: {}", e)))?;
    }

    // ── 3. Write submit file ──
    let sub_path = batch_dir.join("condor.sub");
    let mut sub = String::new();
    sub.push_str("# Auto-generated by myconote-cli batch --condor\n");
    sub.push_str("# Submit with:  condor_submit condor.sub\n\n");
    sub.push_str("universe = vanilla\n");
    sub.push_str(&format!("executable = {}\n", script_path.display()));
    sub.push_str(&format!(
        "arguments = $(Process)\n"
    ));
    sub.push_str(&format!("request_cpus = {}\n", config.cpus));
    sub.push_str(&format!("request_memory = {}\n", config.memory));
    sub.push_str(&format!("request_disk = {}\n", config.disk));
    sub.push('\n');

    // Per-job log/output/error
    sub.push_str(&format!(
        "log    = {}/condor_logs/job_$(Process).log\n",
        batch_dir.display()
    ));
    sub.push_str(&format!(
        "output = {}/condor_logs/job_$(Process).out\n",
        batch_dir.display()
    ));
    sub.push_str(&format!(
        "error  = {}/condor_logs/job_$(Process).err\n",
        batch_dir.display()
    ));
    sub.push('\n');

    // Environment: pass CONDOR_PROCESS_ID
    sub.push_str("environment = \"CONDOR_PROCESS_ID=$(Process)\"\n");

    // Transfer settings — genomes should be on shared filesystem
    sub.push_str("should_transfer_files = IF_NEEDED\n");
    sub.push_str("when_to_transfer_output = ON_EXIT\n");
    sub.push('\n');

    // Accounting group
    if let Some(ref queue) = config.queue {
        sub.push_str(&format!("accounting_group = {}\n", queue));
    }

    // Max idle jobs
    if let Some(max) = config.max_idle {
        sub.push_str(&format!("max_idle = {}\n", max));
    }

    // Extra directives
    if let Some(ref extra_path) = config.extra_file {
        if extra_path.exists() {
            let extra = std::fs::read_to_string(extra_path).map_err(|e| {
                MycoNoteError::BatchError(format!(
                    "cannot read extra submit file {}: {}",
                    extra_path.display(),
                    e
                ))
            })?;
            sub.push_str("\n# Extra directives from user file\n");
            sub.push_str(&extra);
            sub.push('\n');
        }
    }

    sub.push('\n');
    sub.push_str(&format!("queue {}\n", genomes.len()));

    std::fs::write(&sub_path, &sub)
        .map_err(|e| MycoNoteError::BatchError(format!("cannot write submit file: {}", e)))?;

    // Create log directory
    let log_dir = batch_dir.join("condor_logs");
    std::fs::create_dir_all(&log_dir)
        .map_err(|e| MycoNoteError::BatchError(format!("cannot create log dir: {}", e)))?;

    Ok(sub_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn test_generate_condor_submit() {
        let tmp = std::env::temp_dir().join("myconote_condor_test");
        let _ = std::fs::remove_dir_all(&tmp);

        let genomes = vec![
            CondorGenome {
                name: "isolate_A".to_string(),
                fasta_path: "/data/isolate_A.fa".to_string(),
                kingdom: "fungi".to_string(),
                species: None,
                genetic_code: 1,
                locus_prefix: Some("ISOA".to_string()),
            },
            CondorGenome {
                name: "isolate_B".to_string(),
                fasta_path: "/data/isolate_B.fa".to_string(),
                kingdom: "fungi".to_string(),
                species: Some("saccharomyces".to_string()),
                genetic_code: 1,
                locus_prefix: None,
            },
        ];

        let config = CondorConfig::default();
        let stages = vec!["sort", "mask", "predict", "annotate"];

        let sub_path = generate_condor_submit(&tmp, &genomes, &config, &stages, 8).unwrap();

        // Submit file exists
        assert!(sub_path.exists());
        let sub_content = std::fs::read_to_string(&sub_path).unwrap();
        assert!(sub_content.contains("universe = vanilla"));
        assert!(sub_content.contains("request_cpus = 8"));
        assert!(sub_content.contains("request_memory = 32G"));
        assert!(sub_content.contains("queue 2"));

        // Genome list exists
        let list_path = tmp.join("condor_genomes.txt");
        assert!(list_path.exists());
        let list = std::fs::read_to_string(&list_path).unwrap();
        assert!(list.contains("isolate_A"));
        assert!(list.contains("isolate_B"));

        // Wrapper script exists and is executable
        let script = tmp.join("run_genome.sh");
        assert!(script.exists());
        let script_content = std::fs::read_to_string(&script).unwrap();
        assert!(script_content.contains("myconote-cli sort"));
        assert!(script_content.contains("myconote-cli predict"));

        // Log directory exists
        assert!(tmp.join("condor_logs").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_condor_config_default() {
        let cfg = CondorConfig::default();
        assert_eq!(cfg.cpus, 8);
        assert_eq!(cfg.memory, "32G");
        assert_eq!(cfg.disk, "50G");
        assert!(cfg.queue.is_none());
    }

    #[test]
    fn test_empty_genomes_errors() {
        let tmp = std::env::temp_dir().join("myconote_condor_empty");
        let result = generate_condor_submit(
            &tmp,
            &[],
            &CondorConfig::default(),
            &["sort"],
            4,
        );
        assert!(result.is_err());
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
