//! Integration tests for `myconote-cli de-template`.
//!
//! CI-safe tests exercise the CLI surface without R. The `#[ignore]`d
//! live tests run `Rscript --vanilla` to confirm the emitted script is
//! syntactically valid R (runs with `cargo test --release --test
//! de_template_tests -- --ignored` when R is on PATH).

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use tempfile::TempDir;

fn bin() -> Command {
    Command::cargo_bin("myconote-cli").expect("binary not found — run `cargo build` first")
}

fn write_fake_quant_dir(dir: &std::path::Path) -> (std::path::PathBuf, std::path::PathBuf) {
    fs::create_dir_all(dir.join("salmon").join("WT1")).unwrap();
    fs::create_dir_all(dir.join("salmon").join("WT2")).unwrap();
    fs::create_dir_all(dir.join("salmon").join("KO1")).unwrap();
    fs::create_dir_all(dir.join("salmon").join("KO2")).unwrap();

    let sheet = dir.join("sample_sheet.tsv");
    fs::write(
        &sheet,
        "sample_id\tfastq_r1\tfastq_r2\tcondition\n\
         WT1\twt1_R1.fq.gz\twt1_R2.fq.gz\tcontrol\n\
         WT2\twt2_R1.fq.gz\twt2_R2.fq.gz\tcontrol\n\
         KO1\tko1_R1.fq.gz\tko1_R2.fq.gz\ttreated\n\
         KO2\tko2_R1.fq.gz\tko2_R2.fq.gz\ttreated\n",
    )
    .unwrap();

    // Place stub quant.sf files so the samples_sheet check the tool
    // does (via validate_contrasts → parse_sheet) doesn't fail when
    // it resolves the relative path.
    for s in ["WT1", "WT2", "KO1", "KO2"] {
        fs::write(
            dir.join("salmon").join(s).join("quant.sf"),
            "Name\tLength\tEffectiveLength\tTPM\tNumReads\n",
        )
        .unwrap();
    }

    (dir.to_path_buf(), sheet)
}

#[test]
fn de_template_help_shows_usage() {
    bin()
        .args(["de-template", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Usage: myconote-cli de-template"))
        .stdout(predicate::str::contains("REQUIRES"))
        .stdout(predicate::str::contains("BiocManager::install"));
}

#[test]
fn de_template_missing_all_inputs_errors() {
    bin()
        .args(["de-template"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Usage:"));
}

#[test]
fn de_template_missing_design_errors() {
    bin()
        .args([
            "de-template",
            "--quant-dir",
            "nowhere",
            "--contrast",
            "condition,a,b",
        ])
        .assert()
        .failure()
        .stderr(predicate::str::contains("--design"));
}

#[test]
fn de_template_writes_script_for_happy_path() {
    let tmp = TempDir::new().unwrap();
    let quant_dir = tmp.path().join("quant_out");
    let (quant_dir, _sheet) = write_fake_quant_dir(&quant_dir);
    let out = tmp.path().join("analysis.R");

    bin()
        .arg("de-template")
        .arg("--quant-dir")
        .arg(&quant_dir)
        .arg("--design")
        .arg("~ condition")
        .arg("--contrast")
        .arg("condition,treated,control")
        .arg("-o")
        .arg(&out)
        .assert()
        .success()
        .stderr(predicate::str::contains("wrote"));

    assert!(out.is_file(), "expected R script at {}", out.display());
    let body = fs::read_to_string(&out).unwrap();

    // Header identifiers
    assert!(body.starts_with("#!/usr/bin/env Rscript"));
    assert!(body.contains("Auto-generated by myconote-cli de-template"));
    // The user-alert layer inside the script
    assert!(body.contains("BiocManager::install"));
    assert!(body.contains("stop(paste0"));
    // Input substitutions
    assert!(body.contains(&format!(
        "QUANT_DIR            <- \"{}\"",
        quant_dir.display()
    )));
    assert!(body.contains("COUNTS_PATH          <- NULL"));
    assert!(body.contains("DESIGN               <- ~ condition"));
    assert!(body.contains("c(\"condition\", \"treated\", \"control\")"));
    // DESeq2 + plot primitives
    assert!(body.contains("DESeqDataSetFromTximport"));
    assert!(body.contains("lfcShrink(dds"));
    assert!(body.contains("plotMA"));
    assert!(body.contains("sessionInfo()"));
}

#[test]
fn de_template_rejects_unknown_factor() {
    // Contrast references a factor column that is not in the sample
    // sheet — tool should fail before writing the script.
    let tmp = TempDir::new().unwrap();
    let quant_dir = tmp.path().join("quant_out");
    write_fake_quant_dir(&quant_dir);
    let out = tmp.path().join("analysis.R");

    bin()
        .arg("de-template")
        .arg("--quant-dir")
        .arg(&quant_dir)
        .arg("--design")
        .arg("~ condition")
        .arg("--contrast")
        .arg("tissue,brain,liver")
        .arg("-o")
        .arg(&out)
        .assert()
        .failure()
        .stderr(predicate::str::contains("not a column"));

    assert!(
        !out.exists(),
        "script must not be written on validation error"
    );
}

#[test]
fn de_template_rejects_unknown_level() {
    let tmp = TempDir::new().unwrap();
    let quant_dir = tmp.path().join("quant_out");
    write_fake_quant_dir(&quant_dir);
    let out = tmp.path().join("analysis.R");

    bin()
        .arg("de-template")
        .arg("--quant-dir")
        .arg(&quant_dir)
        .arg("--design")
        .arg("~ condition")
        .arg("--contrast")
        .arg("condition,starved,fed") // neither in sheet
        .arg("-o")
        .arg(&out)
        .assert()
        .failure()
        .stderr(predicate::str::contains("not found in column"));
}

#[test]
fn de_template_rejects_injection_design() {
    let tmp = TempDir::new().unwrap();
    let quant_dir = tmp.path().join("quant_out");
    write_fake_quant_dir(&quant_dir);

    bin()
        .arg("de-template")
        .arg("--quant-dir")
        .arg(&quant_dir)
        .arg("--design")
        .arg("~ condition; system(\"id\")")
        .arg("--contrast")
        .arg("condition,treated,control")
        .assert()
        .failure()
        .stderr(predicate::str::contains("statement terminator"));
}

// ── Live R syntactic validation (ignored unless Rscript is on PATH) ────────

#[test]
#[ignore]
fn de_template_emits_syntactically_valid_r() {
    if which::which("Rscript").is_err() {
        eprintln!("Rscript not on PATH — skipping");
        return;
    }

    let tmp = TempDir::new().unwrap();
    let quant_dir = tmp.path().join("quant_out");
    write_fake_quant_dir(&quant_dir);
    let out = tmp.path().join("analysis.R");

    bin()
        .arg("de-template")
        .arg("--quant-dir")
        .arg(&quant_dir)
        .arg("--design")
        .arg("~ condition")
        .arg("--contrast")
        .arg("condition,treated,control")
        .arg("-o")
        .arg(&out)
        .assert()
        .success();

    // `Rscript -e 'parse(...)'` returns nonzero on syntax error
    // *and* prints the failure location. A zero-exit run is our
    // success signal; we don't care about the stdout.
    let status = std::process::Command::new("Rscript")
        .arg("--vanilla")
        .arg("-e")
        .arg(format!("invisible(parse(file = \"{}\"))", out.display()))
        .status()
        .expect("Rscript invocation");
    assert!(
        status.success(),
        "emitted R script is not syntactically valid: {}",
        out.display()
    );
}
