//! Self-contained HTML report for `myconote-cli compare --html`.
//!
//! Produces `compare_out/report.html`: a single HTML file that opens
//! correctly from `file://` with no network access. CSS and JS are
//! embedded via `include_str!` so no external assets ever load. The
//! report carries:
//!
//!   1. Pan-genome summary (core / soft-core / shell / cloud / singleton
//!      counts as a styled table plus a stacked-bar SVG).
//!   2. Per-genome stats (n_proteins, n_orthogroups, % core, % singletons).
//!   3. Sortable ortholog table with a client-side text filter.
//!   4. Inline-SVG species tree from OrthoFinder's rooted Newick.
//!   5. Reproducibility footer (tool versions, run command, input
//!      checksums) so the report itself documents what produced it.
//!
//! No askama, no handlebars, no React. Vanilla HTML built by
//! `tinytemplate` plus a small Newick → SVG renderer below.

use crate::compare::orthofinder::{Orthogroup, PangenomeSummary};
use crate::compare::GenomeInput;
use crate::utils::error::{MycoNoteError, Result};
use serde::Serialize;
use std::io::Write;
use std::path::{Path, PathBuf};
use tinytemplate::TinyTemplate;

const REPORT_CSS: &str = include_str!("report.css");
const REPORT_JS: &str = include_str!("report.js");

const REPORT_TEMPLATE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title | unescaped}</title>
<style>{css | unescaped}</style>
</head>
<body>
<main>
  <h1>{title | unescaped}</h1>
  <p class="subtitle">Comparative-genomics summary across {n_genomes} {genome_word | unescaped}.</p>

  <h2>Pan-genome shape</h2>
  <div class="summary-grid">
    <div class="panel">
      <h3>Cluster counts</h3>
      <table>
        <thead><tr><th>Category</th><th>Clusters</th><th>Fraction</th></tr></thead>
        <tbody>{pangenome_rows | unescaped}</tbody>
      </table>
    </div>
    <div class="panel">
      <h3>Stacked composition</h3>
      <div class="bar-chart">{bar_segments | unescaped}</div>
      <div class="legend">{legend_items | unescaped}</div>
    </div>
  </div>

  <h2>Per-genome statistics</h2>
  <table class="sortable">
    <thead><tr>
      <th data-sortable="1">Genome</th>
      <th data-sortable="1">Proteins</th>
      <th data-sortable="1">Orthogroups</th>
      <th data-sortable="1">% in core</th>
      <th data-sortable="1">% singletons</th>
    </tr></thead>
    <tbody>{per_genome_rows | unescaped}</tbody>
  </table>

  <h2>Ortholog table</h2>
  <input id="ortholog-search" class="search-bar" type="text"
         placeholder="Filter by orthogroup ID or gene name…">
  <table id="ortholog-table" class="sortable">
    <thead><tr>{ortholog_headers | unescaped}</tr></thead>
    <tbody>{ortholog_rows | unescaped}</tbody>
  </table>

  <h2>Species tree</h2>
  {tree_svg | unescaped}

  <div class="footer">
    <h3>Reproducibility</h3>
    <p>Generated by <code>myconote-cli</code> v{tool_version | unescaped} ({git_sha | unescaped})</p>
    <p>Run command: <code>{run_command | unescaped}</code></p>
    <p>Input SHA256s:</p>
    <ul>{input_hashes | unescaped}</ul>
  </div>
</main>
<script>{js | unescaped}</script>
</body>
</html>"#;

#[derive(Serialize)]
struct ReportContext {
    title: String,
    n_genomes: usize,
    genome_word: String,
    css: String,
    js: String,
    pangenome_rows: String,
    bar_segments: String,
    legend_items: String,
    per_genome_rows: String,
    ortholog_headers: String,
    ortholog_rows: String,
    tree_svg: String,
    tool_version: String,
    git_sha: String,
    run_command: String,
    input_hashes: String,
}

/// Per-genome stats row (computed once, used in both the per-genome
/// table and the orthogroup-presence summary).
#[derive(Debug, Clone)]
pub struct PerGenomeStats {
    pub name: String,
    pub n_proteins: usize,
    pub n_orthogroups: usize,
    pub pct_in_core: f64,
    pub pct_singletons: f64,
}

/// Compute per-genome stats from the parsed orthogroup table.
pub fn compute_per_genome_stats(
    inputs: &[GenomeInput],
    protein_counts: &[usize],
    orthogroups: &[Orthogroup],
) -> Vec<PerGenomeStats> {
    let total_genomes = inputs.len();
    let mut out = Vec::with_capacity(inputs.len());
    for (i, g) in inputs.iter().enumerate() {
        let mut n_ogs = 0usize;
        let mut n_in_core = 0usize;
        let mut n_singletons = 0usize;
        for og in orthogroups {
            let here = og
                .members
                .get(&g.name)
                .map(|v| !v.is_empty())
                .unwrap_or(false);
            if !here {
                continue;
            }
            n_ogs += 1;
            if og.n_genomes() == total_genomes {
                n_in_core += 1;
            }
            if og.n_genomes() == 1 {
                n_singletons += 1;
            }
        }
        let pct_core = if n_ogs == 0 {
            0.0
        } else {
            100.0 * n_in_core as f64 / n_ogs as f64
        };
        let pct_singletons = if n_ogs == 0 {
            0.0
        } else {
            100.0 * n_singletons as f64 / n_ogs as f64
        };
        out.push(PerGenomeStats {
            name: g.name.clone(),
            n_proteins: protein_counts.get(i).copied().unwrap_or(0),
            n_orthogroups: n_ogs,
            pct_in_core: pct_core,
            pct_singletons,
        });
    }
    out
}

/// HTML-escape a string for safe inclusion in tag content. We emit
/// every user-supplied ID (gene names, orthogroup IDs, genome names)
/// through this. Five characters → entities; everything else passes
/// through unchanged.
pub fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            other => out.push(other),
        }
    }
    out
}

/// Render the full HTML report and write it to `path`.
#[allow(clippy::too_many_arguments)]
pub fn render_html_report(
    path: &Path,
    inputs: &[GenomeInput],
    protein_counts: &[usize],
    orthogroups: &[Orthogroup],
    summary: &PangenomeSummary,
    species_tree_newick: Option<&str>,
    run_command: &str,
    input_hashes: &[(String, String)],
) -> Result<()> {
    let ctx = build_context(
        inputs,
        protein_counts,
        orthogroups,
        summary,
        species_tree_newick,
        run_command,
        input_hashes,
    );

    let mut tt = TinyTemplate::new();
    tt.add_template("report", REPORT_TEMPLATE)
        .map_err(|e| MycoNoteError::InvalidFormat(format!("template register: {}", e)))?;
    let body = tt
        .render("report", &ctx)
        .map_err(|e| MycoNoteError::InvalidFormat(format!("template render: {}", e)))?;

    let mut f = std::fs::File::create(path).map_err(MycoNoteError::Io)?;
    f.write_all(body.as_bytes()).map_err(MycoNoteError::Io)?;
    Ok(())
}

fn build_context(
    inputs: &[GenomeInput],
    protein_counts: &[usize],
    orthogroups: &[Orthogroup],
    summary: &PangenomeSummary,
    species_tree_newick: Option<&str>,
    run_command: &str,
    input_hashes: &[(String, String)],
) -> ReportContext {
    let n_genomes = inputs.len();

    // ── Pan-genome rows + bar segments ────────────────────────────────
    let bins: [(&str, usize, &str); 5] = [
        ("core", summary.core, "var(--col-core)"),
        ("soft_core", summary.soft_core, "var(--col-soft-core)"),
        ("shell", summary.shell, "var(--col-shell)"),
        ("cloud", summary.cloud, "var(--col-cloud)"),
        ("singletons", summary.singletons, "var(--col-singletons)"),
    ];
    let total_for_bar: usize = bins.iter().map(|(_, n, _)| n).sum();
    let mut pangenome_rows = String::new();
    let mut bar_segments = String::new();
    let mut legend_items = String::new();
    for (label, n, color) in &bins {
        let frac = if summary.total_clusters == 0 {
            0.0
        } else {
            *n as f64 / summary.total_clusters as f64
        };
        pangenome_rows.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{:.1}%</td></tr>",
            escape_html(label),
            n,
            frac * 100.0
        ));
        // Bar segment width as % of bar (skip if zero so we don't render
        // empty zero-width segments that throw off the legend match).
        if *n > 0 && total_for_bar > 0 {
            let pct = 100.0 * (*n as f64) / (total_for_bar as f64);
            bar_segments.push_str(&format!(
                "<div class=\"bar-segment\" style=\"width: {:.2}%; background: {};\" \
                 title=\"{} clusters\">{}</div>",
                pct,
                color,
                n,
                escape_html(label)
            ));
        }
        legend_items.push_str(&format!(
            "<span><span class=\"legend-swatch\" style=\"background: {};\"></span>{} ({})</span>",
            color,
            escape_html(label),
            n
        ));
    }

    // ── Per-genome rows ───────────────────────────────────────────────
    let stats = compute_per_genome_stats(inputs, protein_counts, orthogroups);
    let mut per_genome_rows = String::new();
    for s in &stats {
        per_genome_rows.push_str(&format!(
            "<tr><td>{}</td><td data-sort=\"{}\">{}</td><td data-sort=\"{}\">{}</td>\
             <td data-sort=\"{:.4}\">{:.1}%</td>\
             <td data-sort=\"{:.4}\">{:.1}%</td></tr>",
            escape_html(&s.name),
            s.n_proteins,
            s.n_proteins,
            s.n_orthogroups,
            s.n_orthogroups,
            s.pct_in_core,
            s.pct_in_core,
            s.pct_singletons,
            s.pct_singletons,
        ));
    }

    // ── Ortholog table ────────────────────────────────────────────────
    let mut ortholog_headers = String::new();
    ortholog_headers
        .push_str("<th data-sortable=\"1\">Orthogroup</th><th data-sortable=\"1\">n genomes</th>");
    for g in inputs {
        ortholog_headers.push_str(&format!(
            "<th data-sortable=\"1\">{}</th>",
            escape_html(&g.name)
        ));
    }
    let mut ortholog_rows = String::new();
    // Cap rows to keep the HTML responsive — orthogroup tables can run to
    // tens of thousands of rows for fungal pan-genomes. Users who need
    // every row can read the TSV.
    const MAX_ROWS: usize = 5000;
    let take = orthogroups.len().min(MAX_ROWS);
    for og in orthogroups.iter().take(take) {
        ortholog_rows.push_str("<tr>");
        ortholog_rows.push_str(&format!("<td>{}</td>", escape_html(&og.id)));
        ortholog_rows.push_str(&format!(
            "<td data-sort=\"{}\">{}</td>",
            og.n_genomes(),
            og.n_genomes()
        ));
        for g in inputs {
            let cell = match og.members.get(&g.name) {
                Some(v) if !v.is_empty() => v
                    .iter()
                    .map(|s| escape_html(s))
                    .collect::<Vec<_>>()
                    .join(", "),
                _ => "—".to_string(),
            };
            ortholog_rows.push_str(&format!("<td>{}</td>", cell));
        }
        ortholog_rows.push_str("</tr>");
    }
    if orthogroups.len() > MAX_ROWS {
        ortholog_rows.push_str(&format!(
            "<tr><td colspan=\"{}\" class=\"no-data\">… {} of {} orthogroups shown. \
             Read <code>ortholog_table.tsv</code> for the full list.</td></tr>",
            inputs.len() + 2,
            MAX_ROWS,
            orthogroups.len()
        ));
    }

    // ── Species tree SVG ──────────────────────────────────────────────
    let tree_svg = match species_tree_newick {
        Some(nwk) if !nwk.trim().is_empty() => render_tree_svg(nwk).unwrap_or_else(|e| {
            format!(
                "<p class=\"no-data\">Tree render failed: {}</p>",
                escape_html(&e)
            )
        }),
        _ => "<p class=\"no-data\">No species tree available (need ≥3 genomes \
              for OrthoFinder to root one).</p>"
            .to_string(),
    };

    // ── Reproducibility footer ────────────────────────────────────────
    let mut input_hashes_html = String::new();
    for (name, sha) in input_hashes {
        input_hashes_html.push_str(&format!(
            "<li><code>{}</code> &mdash; <code>{}</code></li>",
            escape_html(name),
            escape_html(sha)
        ));
    }
    if input_hashes_html.is_empty() {
        input_hashes_html.push_str("<li class=\"no-data\">No input checksums recorded.</li>");
    }

    let git_sha = option_env!("GIT_SHA").unwrap_or("untracked").to_string();

    ReportContext {
        title: "MycoNote-CLI compare report".to_string(),
        n_genomes,
        genome_word: if n_genomes == 1 {
            "genome".into()
        } else {
            "genomes".into()
        },
        css: REPORT_CSS.to_string(),
        js: REPORT_JS.to_string(),
        pangenome_rows,
        bar_segments,
        legend_items,
        per_genome_rows,
        ortholog_headers,
        ortholog_rows,
        tree_svg,
        tool_version: env!("CARGO_PKG_VERSION").to_string(),
        git_sha,
        run_command: escape_html(run_command),
        input_hashes: input_hashes_html,
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Newick → SVG tree renderer
// ─────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct TreeNode {
    pub label: String,
    pub branch_length: f64,
    pub children: Vec<TreeNode>,
}

impl TreeNode {
    pub fn is_leaf(&self) -> bool {
        self.children.is_empty()
    }

    pub fn collect_leaves<'a>(&'a self, out: &mut Vec<&'a TreeNode>) {
        if self.is_leaf() {
            out.push(self);
        } else {
            for c in &self.children {
                c.collect_leaves(out);
            }
        }
    }
}

/// Parse a rooted Newick string into a TreeNode. Supports standard
/// nested form `((a:0.1,b:0.2):0.05,c:0.3);` plus internal labels.
/// Returns the root.
///
/// Validation: input must start with `(` (compound tree) or end with
/// `;` (a single-leaf or simple tree explicitly terminated). Bare
/// strings without either marker are rejected — they're more likely
/// truncated files or non-Newick text than legitimate single-leaf
/// trees, and silently accepting them masks real errors.
pub fn parse_newick(input: &str) -> std::result::Result<TreeNode, String> {
    let trimmed = input.trim();
    if trimmed.is_empty() {
        return Err("empty Newick input".into());
    }
    let starts_compound = trimmed.starts_with('(');
    let has_terminator = trimmed.ends_with(';');
    if !starts_compound && !has_terminator {
        return Err(format!(
            "not a Newick tree: expected '(' to open or ';' to terminate, got {:?}",
            if trimmed.len() > 32 {
                format!("{}…", &trimmed[..32])
            } else {
                trimmed.to_string()
            }
        ));
    }
    let trimmed = trimmed.strip_suffix(';').unwrap_or(trimmed);
    let bytes = trimmed.as_bytes();
    let mut pos = 0usize;
    let node = parse_subtree(bytes, &mut pos)?;
    while pos < bytes.len() && bytes[pos].is_ascii_whitespace() {
        pos += 1;
    }
    if pos != bytes.len() {
        return Err(format!(
            "trailing junk after tree at byte {}: {:?}",
            pos,
            std::str::from_utf8(&bytes[pos..]).unwrap_or("<non-utf8>")
        ));
    }
    Ok(node)
}

fn parse_subtree(b: &[u8], pos: &mut usize) -> std::result::Result<TreeNode, String> {
    skip_ws(b, pos);
    let mut children = Vec::new();
    if *pos < b.len() && b[*pos] == b'(' {
        *pos += 1;
        loop {
            children.push(parse_subtree(b, pos)?);
            skip_ws(b, pos);
            if *pos >= b.len() {
                return Err("unexpected EOF inside subtree".into());
            }
            match b[*pos] {
                b',' => {
                    *pos += 1;
                    continue;
                }
                b')' => {
                    *pos += 1;
                    break;
                }
                other => {
                    return Err(format!(
                        "expected ',' or ')' at byte {}, got {:?}",
                        *pos, other as char
                    ));
                }
            }
        }
    }
    let (label, branch_length) = parse_node_tail(b, pos)?;
    Ok(TreeNode {
        label,
        branch_length,
        children,
    })
}

fn parse_node_tail(b: &[u8], pos: &mut usize) -> std::result::Result<(String, f64), String> {
    skip_ws(b, pos);
    let label_start = *pos;
    while *pos < b.len() {
        let c = b[*pos];
        if c == b':' || c == b',' || c == b')' || c == b';' {
            break;
        }
        *pos += 1;
    }
    let label = std::str::from_utf8(&b[label_start..*pos])
        .map_err(|e| format!("non-utf8 label: {}", e))?
        .trim()
        .to_string();

    let mut bl = 0.0f64;
    if *pos < b.len() && b[*pos] == b':' {
        *pos += 1;
        let bl_start = *pos;
        while *pos < b.len() {
            let c = b[*pos];
            if c == b',' || c == b')' || c == b';' {
                break;
            }
            *pos += 1;
        }
        let bl_str = std::str::from_utf8(&b[bl_start..*pos])
            .map_err(|e| format!("non-utf8 branch length: {}", e))?
            .trim();
        bl = bl_str
            .parse::<f64>()
            .map_err(|_| format!("invalid branch length: {:?}", bl_str))?;
    }

    Ok((label, bl))
}

fn skip_ws(b: &[u8], pos: &mut usize) {
    while *pos < b.len() && b[*pos].is_ascii_whitespace() {
        *pos += 1;
    }
}

/// Render a Newick tree as a horizontal-ladder SVG. Branch lengths
/// scale with the longest root-to-leaf depth so the chart is readable
/// regardless of tree size. Returns the SVG markup as a String.
pub fn render_tree_svg(newick: &str) -> std::result::Result<String, String> {
    let tree = parse_newick(newick)?;
    let mut leaves: Vec<&TreeNode> = Vec::new();
    tree.collect_leaves(&mut leaves);
    if leaves.is_empty() {
        return Err("tree has no leaves".into());
    }

    let leaf_count = leaves.len();
    let leaf_h = 22.0_f64;
    let label_w = 220.0_f64;
    let tree_w = 480.0_f64;
    let margin = 24.0_f64;
    let total_h = margin * 2.0 + leaf_count as f64 * leaf_h;
    let total_w = margin * 2.0 + tree_w + label_w;

    // Compute per-node depths (root-to-node sum of branch_length).
    let max_depth = max_depth(&tree, 0.0);
    let scale = if max_depth > 0.0 {
        tree_w / max_depth
    } else {
        // Topology only — equal spacing per parent.
        tree_w / (1.0_f64.max(deepest_topology(&tree, 0) as f64))
    };

    // Lay out each leaf at a fixed y; intermediate nodes are the mean
    // of their children's y. We accumulate lines while walking the tree.
    let mut svg = String::new();
    svg.push_str(&format!(
        "<svg class=\"tree-svg\" xmlns=\"http://www.w3.org/2000/svg\" \
         width=\"{w:.0}\" height=\"{h:.0}\" viewBox=\"0 0 {w:.0} {h:.0}\">",
        w = total_w,
        h = total_h
    ));

    let mut leaf_index = 0usize;
    layout_and_emit(
        &tree,
        0.0,
        scale,
        margin,
        margin,
        leaf_h,
        max_depth > 0.0,
        &mut leaf_index,
        &mut svg,
    );

    svg.push_str("</svg>");
    Ok(svg)
}

fn max_depth(node: &TreeNode, acc: f64) -> f64 {
    let here = acc + node.branch_length;
    if node.is_leaf() {
        here
    } else {
        node.children
            .iter()
            .map(|c| max_depth(c, here))
            .fold(here, f64::max)
    }
}

fn deepest_topology(node: &TreeNode, depth: usize) -> usize {
    if node.is_leaf() {
        depth
    } else {
        node.children
            .iter()
            .map(|c| deepest_topology(c, depth + 1))
            .max()
            .unwrap_or(depth)
    }
}

#[allow(clippy::too_many_arguments)]
fn layout_and_emit(
    node: &TreeNode,
    parent_x: f64,
    scale: f64,
    x_origin: f64,
    y_origin: f64,
    leaf_h: f64,
    has_branch_lengths: bool,
    leaf_idx: &mut usize,
    out: &mut String,
) -> f64 {
    let edge_dx = if has_branch_lengths {
        node.branch_length * scale
    } else if node.is_leaf() {
        scale
    } else {
        scale.min(80.0)
    };
    let my_x = parent_x + edge_dx;

    if node.is_leaf() {
        let y = y_origin + (*leaf_idx as f64 + 0.5) * leaf_h;
        // Horizontal branch from parent_x → my_x at y.
        out.push_str(&format!(
            "<path class=\"tree-branch\" d=\"M {:.1} {:.1} L {:.1} {:.1}\"/>",
            x_origin + parent_x,
            y,
            x_origin + my_x,
            y
        ));
        // Leaf label.
        out.push_str(&format!(
            "<text class=\"tree-leaf-label\" x=\"{:.1}\" y=\"{:.1}\" \
             dominant-baseline=\"middle\">{}</text>",
            x_origin + my_x + 6.0,
            y,
            escape_html(&node.label)
        ));
        *leaf_idx += 1;
        return y;
    }

    let mut child_ys = Vec::with_capacity(node.children.len());
    for child in &node.children {
        let cy = layout_and_emit(
            child,
            my_x,
            scale,
            x_origin,
            y_origin,
            leaf_h,
            has_branch_lengths,
            leaf_idx,
            out,
        );
        child_ys.push(cy);
    }
    let my_y =
        (child_ys.first().copied().unwrap_or(0.0) + child_ys.last().copied().unwrap_or(0.0)) / 2.0;
    // Vertical bar joining child branches.
    let y_min = child_ys.iter().cloned().fold(f64::INFINITY, f64::min);
    let y_max = child_ys.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    out.push_str(&format!(
        "<path class=\"tree-branch\" d=\"M {:.1} {:.1} L {:.1} {:.1}\"/>",
        x_origin + my_x,
        y_min,
        x_origin + my_x,
        y_max
    ));
    // Branch from parent to this node.
    out.push_str(&format!(
        "<path class=\"tree-branch\" d=\"M {:.1} {:.1} L {:.1} {:.1}\"/>",
        x_origin + parent_x,
        my_y,
        x_origin + my_x,
        my_y
    ));
    my_y
}

/// Compute SHA256 of a file's bytes for the reproducibility footer.
/// Returns the hex digest. The file is streamed to avoid loading
/// large genome FASTAs into memory.
pub fn sha256_file(path: &Path) -> Result<String> {
    use sha2::{Digest, Sha256};
    let mut f = std::fs::File::open(path).map_err(MycoNoteError::Io)?;
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = std::io::Read::read(&mut f, &mut buf).map_err(MycoNoteError::Io)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    let digest = hasher.finalize();
    Ok(format!("{:x}", digest))
}

/// Convenience: collect SHA256 digests for every input genome's GFF +
/// FASTA. Skipped on read errors (logged, not fatal — we'd rather emit
/// the report than refuse it on a permission glitch).
pub fn collect_input_hashes(inputs: &[GenomeInput]) -> Vec<(String, String)> {
    let mut out = Vec::with_capacity(inputs.len() * 2);
    for g in inputs {
        for path in [&g.gff, &g.fasta] {
            match sha256_file(path) {
                Ok(h) => out.push((path.display().to_string(), h)),
                Err(e) => out.push((
                    path.display().to_string(),
                    format!("(hash unavailable: {})", e),
                )),
            }
        }
    }
    out
}

/// Read OrthoFinder's species_tree.nwk if present, returning the
/// trimmed Newick string.
pub fn read_species_tree(path: &PathBuf) -> Option<String> {
    if !path.exists() {
        return None;
    }
    let s = std::fs::read_to_string(path).ok()?;
    let trimmed = s.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn fixture_summary() -> PangenomeSummary {
        PangenomeSummary {
            total_clusters: 100,
            core: 60,
            soft_core: 5,
            shell: 20,
            cloud: 10,
            singletons: 5,
            single_copy_core: 50,
        }
    }

    fn fixture_inputs() -> Vec<GenomeInput> {
        vec![
            GenomeInput {
                name: "genome_a".into(),
                gff: PathBuf::from("a.gff3"),
                fasta: PathBuf::from("a.fa"),
            },
            GenomeInput {
                name: "genome_b".into(),
                gff: PathBuf::from("b.gff3"),
                fasta: PathBuf::from("b.fa"),
            },
            GenomeInput {
                name: "genome_c".into(),
                gff: PathBuf::from("c.gff3"),
                fasta: PathBuf::from("c.fa"),
            },
        ]
    }

    fn fixture_orthogroups() -> Vec<Orthogroup> {
        let mut og0 = Orthogroup {
            id: "OG0000000".into(),
            members: HashMap::new(),
        };
        og0.members.insert("genome_a".into(), vec!["gA1".into()]);
        og0.members.insert("genome_b".into(), vec!["gB1".into()]);
        og0.members.insert("genome_c".into(), vec!["gC1".into()]);

        let mut og1 = Orthogroup {
            id: "OG0000001".into(),
            members: HashMap::new(),
        };
        og1.members.insert("genome_a".into(), vec!["gA2".into()]);
        og1.members.insert("genome_b".into(), vec![]);
        og1.members.insert("genome_c".into(), vec![]);

        vec![og0, og1]
    }

    // ── escape_html ────────────────────────────────────────────────────

    #[test]
    fn escape_html_escapes_all_five_characters() {
        let s = "a&b<c>d\"e'f";
        let esc = escape_html(s);
        assert!(esc.contains("&amp;"));
        assert!(esc.contains("&lt;"));
        assert!(esc.contains("&gt;"));
        assert!(esc.contains("&quot;"));
        assert!(esc.contains("&#39;"));
        assert!(!esc.contains("<c>"));
        assert!(!esc.contains("\"e"));
    }

    #[test]
    fn escape_html_passes_through_unicode() {
        let s = "α β γ δ";
        let esc = escape_html(s);
        assert_eq!(esc, s);
    }

    #[test]
    fn escape_html_neutralises_xss_payload() {
        // Exact payload an attacker would put in a gene ID column.
        let payload = "<script>alert('xss')</script>";
        let esc = escape_html(payload);
        assert!(!esc.contains("<script"));
        assert!(esc.contains("&lt;script"));
    }

    // ── render_html_report ─────────────────────────────────────────────

    #[test]
    fn render_html_report_produces_non_empty_output() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("report.html");
        let inputs = fixture_inputs();
        let counts = vec![1000, 1100, 1200];
        let ogs = fixture_orthogroups();
        let summary = fixture_summary();
        render_html_report(
            &out,
            &inputs,
            &counts,
            &ogs,
            &summary,
            Some("(genome_a:0.1,(genome_b:0.05,genome_c:0.05):0.02);"),
            "myconote-cli compare a.gff3 a.fa b.gff3 b.fa c.gff3 c.fa --html",
            &[],
        )
        .unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.len() > 1000, "report too small: {} bytes", body.len());
        // Skeleton sanity.
        assert!(body.contains("<!DOCTYPE html>"));
        assert!(body.contains("MycoNote-CLI compare report"));
        // Spec compliance: panel labels.
        assert!(body.contains("Pan-genome shape"));
        assert!(body.contains("Per-genome statistics"));
        assert!(body.contains("Ortholog table"));
        assert!(body.contains("Species tree"));
        // CSS / JS embedded.
        assert!(body.contains("--col-core:"));
        assert!(body.contains("attachSort"));
        // Genome names rendered.
        assert!(body.contains("genome_a"));
        assert!(body.contains("genome_b"));
        assert!(body.contains("genome_c"));
        // No external assets.
        assert!(
            !body.contains("https://"),
            "report must not load external resources"
        );
        assert!(
            !body.contains("<link"),
            "report must not <link> external CSS"
        );
    }

    #[test]
    fn render_html_report_xss_safe_for_gene_ids() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("xss.html");
        let inputs = fixture_inputs();
        let mut og = Orthogroup {
            id: "OG_evil".into(),
            members: HashMap::new(),
        };
        og.members.insert(
            "genome_a".into(),
            vec!["<script>alert('pwned')</script>".to_string()],
        );
        og.members.insert("genome_b".into(), vec![]);
        og.members.insert("genome_c".into(), vec![]);
        let ogs = vec![og];
        render_html_report(
            &out,
            &inputs,
            &[1, 1, 1],
            &ogs,
            &fixture_summary(),
            None,
            "myconote-cli compare ... --html",
            &[],
        )
        .unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        // Raw script tag with the gene-ID payload must not appear.
        assert!(!body.contains("<script>alert('pwned')</script>"));
        // The escaped form must appear.
        assert!(body.contains("&lt;script&gt;"));
    }

    // ── Newick parser + tree SVG ──────────────────────────────────────

    #[test]
    fn parse_newick_simple_three_taxon() {
        let tree = parse_newick("(a:0.1,(b:0.2,c:0.3):0.05);").unwrap();
        let mut leaves = Vec::new();
        tree.collect_leaves(&mut leaves);
        assert_eq!(leaves.len(), 3);
        let labels: Vec<&str> = leaves.iter().map(|n| n.label.as_str()).collect();
        assert!(labels.contains(&"a"));
        assert!(labels.contains(&"b"));
        assert!(labels.contains(&"c"));
    }

    #[test]
    fn parse_newick_handles_internal_labels() {
        let tree = parse_newick("(a:0.1,(b:0.2,c:0.3)inode:0.05)root;").unwrap();
        assert_eq!(tree.label, "root");
        // Internal node label preserved.
        assert!(tree
            .children
            .iter()
            .any(|c| c.label == "inode" && !c.is_leaf()));
    }

    #[test]
    fn parse_newick_rejects_garbage() {
        let err = parse_newick("not a tree").unwrap_err();
        assert!(!err.is_empty());
        let err = parse_newick("(a,b").unwrap_err();
        assert!(!err.is_empty());
    }

    #[test]
    fn render_tree_svg_emits_every_leaf() {
        let svg = render_tree_svg("(genome_a:0.1,(genome_b:0.2,genome_c:0.3):0.05);").unwrap();
        assert!(svg.starts_with("<svg"));
        assert!(svg.ends_with("</svg>"));
        // Every leaf label must appear in the SVG output as a <text>
        // tag; this is the spec-required invariant.
        assert!(svg.contains(">genome_a<"));
        assert!(svg.contains(">genome_b<"));
        assert!(svg.contains(">genome_c<"));
        // Each leaf has at least one branch path. Three leaves → at
        // least three <path> elements (typically more for verticals).
        let n_paths = svg.matches("<path ").count();
        assert!(n_paths >= 3, "expected ≥3 paths, got {}", n_paths);
    }

    #[test]
    fn render_tree_svg_handles_unrooted_polytomy() {
        // Five-way star polytomy without branch lengths.
        let svg = render_tree_svg("(a,b,c,d,e);").unwrap();
        for leaf in &["a", "b", "c", "d", "e"] {
            assert!(
                svg.contains(&format!(">{}<", leaf)),
                "missing leaf {}",
                leaf
            );
        }
    }

    #[test]
    fn render_tree_svg_escapes_xss_in_leaf_labels() {
        // If a user-supplied genome name contained an angle bracket the
        // rendered SVG must not let it escape into markup. (Real
        // OrthoFinder species names won't, but defence in depth.)
        let svg = render_tree_svg("(genome<a>:0.1,b:0.2);").unwrap();
        assert!(!svg.contains(">genome<a><"));
        assert!(svg.contains("genome&lt;a&gt;"));
    }

    // ── Per-genome stats ──────────────────────────────────────────────

    #[test]
    fn per_genome_stats_three_genome_fixture() {
        let inputs = fixture_inputs();
        let counts = vec![1000, 1100, 1200];
        let ogs = fixture_orthogroups();
        let stats = compute_per_genome_stats(&inputs, &counts, &ogs);
        assert_eq!(stats.len(), 3);
        // genome_a is in 2/2 of its orthogroups; one is core, one is
        // singleton → 50% core, 50% singleton.
        let a = stats.iter().find(|s| s.name == "genome_a").unwrap();
        assert_eq!(a.n_orthogroups, 2);
        assert_eq!(a.n_proteins, 1000);
        assert!((a.pct_in_core - 50.0).abs() < 1e-9);
        assert!((a.pct_singletons - 50.0).abs() < 1e-9);
        // genome_b is in 1/2 (only the core one).
        let b = stats.iter().find(|s| s.name == "genome_b").unwrap();
        assert_eq!(b.n_orthogroups, 1);
        assert!((b.pct_in_core - 100.0).abs() < 1e-9);
    }
}
