use crate::update::{UpdateConfig, UpdateResult};
/// PASA-based gene model update
///
/// PASA (Program to Assemble Spliced Alignments) builds a transcript alignment
/// database and uses it to update gene model structures — adding UTRs,
/// correcting intron/exon boundaries, and finding alternative isoforms.
///
/// http://pasapipeline.github.io/
/// Install: conda install -c bioconda pasa
use crate::utils::error::{MycoNoteError, Result};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Check if PASA Launch_PASA_pipeline.pl is in PATH
pub fn pasa_available() -> bool {
    Command::new("Launch_PASA_pipeline.pl")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Full PASA-based update workflow.
pub fn run_pasa_update(
    config: &UpdateConfig,
    _bam_path: &Path, // BAM used only for lightweight fallback; PASA re-aligns internally
    transcripts: Option<&Path>,
) -> Result<UpdateResult> {
    let pasa_dir = config.out_dir.join("pasa_update");
    std::fs::create_dir_all(&pasa_dir).map_err(MycoNoteError::Io)?;

    // PASA needs a transcript FASTA
    let tx_fa = match transcripts {
        Some(p) => p.to_path_buf(),
        None => {
            return Err(MycoNoteError::InvalidFormat(
                "PASA update requires a transcript FASTA (--transcripts)".to_string(),
            ))
        }
    };

    // ── Write PASA config file ────────────────────────────────────────────────
    let db_name = config.pasa_db.clone().unwrap_or_else(|| {
        pasa_dir
            .join("pasa_db.sqlite")
            .to_string_lossy()
            .to_string()
    });

    let conf_path = pasa_dir.join("pasa.config");
    write_pasa_config(&conf_path, &db_name, config)?;

    // ── Step 1: Load transcripts into PASA (align + assemble) ───────────────
    let load_status = Command::new("Launch_PASA_pipeline.pl")
        .args([
            "-c",
            conf_path.to_str().unwrap_or(""),
            "-C", // create new database
            "-R", // run pipeline
            "-g",
            config.fasta.to_str().unwrap_or(""),
            "-t",
            tx_fa.to_str().unwrap_or(""),
            "--ALIGNERS",
            "minimap2",
            "--CPU",
            &config.threads.to_string(),
        ])
        .current_dir(&pasa_dir)
        .status()
        .map_err(|e| MycoNoteError::ExternalTool(format!("Launch_PASA_pipeline.pl: {}", e)))?;

    if !load_status.success() {
        return Err(MycoNoteError::ExternalTool(
            "PASA pipeline failed during transcript loading".to_string(),
        ));
    }

    // ── Step 2: Annotation comparison + update ─────────────────────────────
    let ann_compare_out = pasa_dir.join("annotation_compare.txt");
    let update_status = Command::new("Launch_PASA_pipeline.pl")
        .args([
            "-c",
            conf_path.to_str().unwrap_or(""),
            "-A", // annotation comparison mode
            "-g",
            config.fasta.to_str().unwrap_or(""),
            "-t",
            tx_fa.to_str().unwrap_or(""),
            "--TRANSDECODER",
            "--annots",
            config.gff.to_str().unwrap_or(""),
            "--CPU",
            &config.threads.to_string(),
            "--out",
            ann_compare_out.to_str().unwrap_or(""),
        ])
        .current_dir(&pasa_dir)
        .status()
        .map_err(|e| MycoNoteError::ExternalTool(format!("Launch_PASA_pipeline.pl -A: {}", e)))?;

    if !update_status.success() {
        return Err(MycoNoteError::ExternalTool(
            "PASA annotation comparison/update failed".to_string(),
        ));
    }

    // ── Find updated GFF3 output ──────────────────────────────────────────────
    // PASA generates e.g. <db_name>.gene_structures_post_PASA_updates.*.gff3
    let updated_gff = find_pasa_output_gff(&pasa_dir)?;

    // ── Parse change statistics from PASA log ────────────────────────────────
    let (n_total, n_updated, n_utr5, n_utr3, n_iso) = parse_pasa_stats(&ann_compare_out);

    // Copy updated GFF to canonical output location
    let out_gff = config.out_dir.join("updated.gff3");
    std::fs::copy(&updated_gff, &out_gff).map_err(MycoNoteError::Io)?;

    Ok(UpdateResult {
        output_gff: out_gff,
        n_genes_total: n_total,
        n_genes_updated: n_updated,
        n_utr5_added: n_utr5,
        n_utr3_added: n_utr3,
        n_isoforms_added: n_iso,
        pasa_used: true,
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn write_pasa_config(conf: &Path, db_name: &str, config: &UpdateConfig) -> Result<()> {
    let mut f = std::fs::File::create(conf).map_err(MycoNoteError::Io)?;
    let org = config.organism.as_deref().unwrap_or("myconote_organism");

    writeln!(f, "# PASA configuration - generated by myconote").map_err(MycoNoteError::Io)?;
    writeln!(f, "DATABASE={}", db_name).map_err(MycoNoteError::Io)?;
    writeln!(f, "MYSQLDB={}", db_name).map_err(MycoNoteError::Io)?; // PASA compat
    writeln!(f, "ORGANISM_NAME={}", org).map_err(MycoNoteError::Io)?;
    writeln!(f, "MAX_INTRON_LENGTH=10000").map_err(MycoNoteError::Io)?;
    writeln!(f, "MIN_PERCENT_ALIGNED=75").map_err(MycoNoteError::Io)?;
    writeln!(f, "MIN_AVG_PER_ID=95").map_err(MycoNoteError::Io)?;

    Ok(())
}

fn find_pasa_output_gff(pasa_dir: &Path) -> Result<PathBuf> {
    let entries = std::fs::read_dir(pasa_dir).map_err(MycoNoteError::Io)?;
    for entry in entries.flatten() {
        let name = entry.file_name();
        let s = name.to_string_lossy();
        if s.contains("post_PASA_updates") && s.ends_with(".gff3") {
            return Ok(entry.path());
        }
    }
    // Fallback: look for any *updated*.gff3
    let entries2 = std::fs::read_dir(pasa_dir).map_err(MycoNoteError::Io)?;
    for entry in entries2.flatten() {
        let s = entry.file_name().to_string_lossy().to_string();
        if s.ends_with(".gff3") {
            return Ok(entry.path());
        }
    }
    Err(MycoNoteError::InvalidFormat(
        "Could not find PASA updated GFF3 output".to_string(),
    ))
}

fn parse_pasa_stats(log: &Path) -> (usize, usize, usize, usize, usize) {
    use std::io::BufRead;
    let mut n_total = 0usize;
    let mut n_updated = 0usize;
    let mut n_utr5 = 0usize;
    let mut n_utr3 = 0usize;
    let mut n_iso = 0usize;

    if let Ok(file) = std::fs::File::open(log) {
        for line in std::io::BufReader::new(file).lines().flatten() {
            // PASA annotation comparison lines contain counts like
            //   #Total genes: 8000
            //   #Updated: 1500
            //   #5prime_UTR: 900
            //   #3prime_UTR: 950
            //   #alt_isoform: 200
            if line.contains("Total genes:") {
                n_total = extract_number(&line);
            } else if line.contains("Updated:") {
                n_updated = extract_number(&line);
            } else if line.contains("5prime_UTR:") || line.contains("5'UTR") {
                n_utr5 = extract_number(&line);
            } else if line.contains("3prime_UTR:") || line.contains("3'UTR") {
                n_utr3 = extract_number(&line);
            } else if line.to_lowercase().contains("isoform") {
                n_iso = extract_number(&line);
            }
        }
    }

    (n_total, n_updated, n_utr5, n_utr3, n_iso)
}

fn extract_number(s: &str) -> usize {
    s.split_whitespace()
        .rev()
        .find_map(|tok| tok.parse::<usize>().ok())
        .unwrap_or(0)
}
